"""note table

Revision ID: 5cefef33a263
Revises: 
Create Date: 2024-03-31 23:12:15.168851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cefef33a263'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('symptoms', sa.String(length=140), nullable=True),
    sa.Column('notes', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_notes'), ['notes'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_symptoms'), ['symptoms'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_title'))
        batch_op.drop_index(batch_op.f('ix_note_symptoms'))
        batch_op.drop_index(batch_op.f('ix_note_notes'))

    op.drop_table('note')
    # ### end Alembic commands ###
